### ISSUE TITLE
Server crash due to error during startup on Linux

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#814]
How to reproduce:
1. Occupy port 8080 with something. In my case this was nginx inside of podman
2. Leave default game server port (7777) in `server-settings.json`

Linux Distro: Ubuntu 20.04 (container)

```
[2022-01-21 14:10:30.490] [console] [error] Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at new y (/home/roma/my/skymp/skymp-focal/build/dist/server/dist_back/skymp5-server.js:700:1650)
    at Object.p [as main] (/home/roma/my/skymp/skymp-focal/build/dist/server/dist_back/skymp5-server.js:704:1283)
    at /home/roma/my/skymp/skymp-focal/build/dist/server/dist_back/skymp5-server.js:780:4165
    at Generator.next (<anonymous>)
    at s (/home/roma/my/skymp/skymp-focal/build/dist/server/dist_back/skymp5-server.js:780:660)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
...
(gdb) bt
#0  0x00007f2ffe8d3189 in Memory::ArenaAllocatorBase<Memory::InPlaceFreeListPolicy, 4ul, false, 0ul>::Clear (this=0x7f3014022008) at /src/vcpkg/buildtrees/chakracore/x64-linux/lib/Common/Memory/ArenaAllocator.h:207
#1  0x00007f2ffeaaa185 in Js::TempArenaAllocatorWrapper<true>::Dispose (this=0x7f3014022000, isShutdown=true) at /src/vcpkg/buildtrees/chakracore/x64-linux/lib/Runtime/Base/TempArenaAllocatorObject.cpp:32
...
```

Full stacktrace: https://gist.github.com/nic11/d8a27b746f94480d68e4e10d8a511cee

**Comment by Pospelove** [comment]
won't fix (probably)
