### ISSUE TITLE
Change error to warning - Anomally, baseId should never change

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#879]
It seems that updating esp introduces this error

```
[2022-01-27 16:51:24.000] [console] [error] Error: Anomally, baseId should never change (63d296b => 623f6c0)
    at t.setUserActor (/skymp5-server/ts/nativeGameServer.ts:29:34)
    at EventEmitter.<anonymous> (/skymp5-server/ts/systems/spawn.ts:32:17)
    at EventEmitter.emit (events.js:400:28)
    at /skymp5-server/ts/systems/login.ts:58:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5) Promise {
  <rejected> Error: Anomally, baseId should never change (63d296b => 623f6c0)
      at t.setUserActor (/skymp5-server/ts/nativeGameServer.ts:29:34)
      at EventEmitter.<anonymous> (/skymp5-server/ts/systems/spawn.ts:32:17)
      at EventEmitter.emit (events.js:400:28)
      at /skymp5-server/ts/systems/login.ts:58:18
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
```

**Comment by nic11** [comment]
Also, should be just 'anomaly' (one l)

**Comment by Pospelove** [comment]
no activity. will probably get back to this
