### ISSUE TITLE
Some players can't be damaged by some others (not all)

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#927]
Below was a wrong one apparently.

I believe this is the right error:
```
[2022-02-07 08:43:35.382] [console] [error] in server.tick:
Error: Form with id 623a59c is not Actor
    at ScampServer.tick (<anonymous>)
    at /skymp5-server/ts/index.ts:159:16
    at Generator.next (<anonymous>)
    at s (/skymp5-server/ts/index.ts:312:1)
```

```
b skymp5-server/cpp/server_guest_lib/WorldState.h:88
b skymp5-server/cpp/server_guest_lib/WorldState.h:95
b skymp5-server/cpp/server_guest_lib/WorldState.cpp:101
```

~~Happens randomly, apparently is caused by this error: \
https://github.com/skyrim-multiplayer/skymp/blob/f1ff95b43253f8201207615abf33d685a132629c/skymp5-server/cpp/server_guest_lib/WorldState.cpp#L101-L105

Breakpoint template: `b skymp5-server/cpp/server_guest_lib/WorldState.cpp:101`~~

- https://discord.com/channels/699653182946803722/938471682706923601/938841340018573432
- https://discord.com/channels/699653182946803722/938471682706923601/939529204414971924
- https://discord.com/channels/699653182946803722/938471682706923601/939531586477654026

**Comment by nic11** [comment]
Fixed by #1002
